name: Action Sample

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      # - uses: RafikFarhad/push-to-gcr-github-action@v4
      #   with:
      #     gcloud_service_key: ${{ secrets.GCP_AUTH }}
      #     registry: gcr.io
      #     project_id: asterism-351904
      #     image_name: asterism-end

      - name: ls test
        run: |
          ls && \
          docker -v && \
          gcloud \
