name: Action Sample

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      # - uses: RafikFarhad/push-to-gcr-github-action@v4
      #   with:
      #     gcloud_service_key: ${{ secrets.GCP_AUTH }}
      #     registry: gcr.io
      #     project_id: asterism-351904
      #     image_name: asterism-end
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          private-key: ${{ secrets.GCP_SSH_KEY }}
          name: id_rsa
          known-hosts: ${{ secrets.GCP_SSH_KEY_PUB }}
          config: |
            Host 35.223.124.139
              HostName 35.223.124.139
              User haruharuharu0328
              IdentityFile ~/.ssh/id_rsa

      - name: ssh test
        run: | 
          ssh -T haruharuharu0328@35.223.124.139 && \
          ls